name: plugin_and_test_pipeline
argo_version_lock: true
#cluster_name at the pipeline level means that every step in the pipeline will deploy to cluster_local.
#If cluster_name is also defined at a particular step, it will override the cluster_name set at the pipeline
#(only for that step).
cluster_name: in-cluster
steps:
- name: deploy_to_dev
  #This is the path of the ArgoCD Application file
  application_path: testapp_dev.yml
- name: deploy_to_int
  application_path: testapp_int.yml
  dependencies:
  - deploy_to_dev
